name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
  schedule:
    # 9:23 AM EST
    - cron: "23 13 * * *"

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dkotlin.incremental=false -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.logging.stacktrace=full"

jobs:
  workflow-up-to-date:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: brew update && brew install d2
      - run: pip install -r .github/requirements.txt
      - run: .github/helper.py generate
      - run: git diff --exit-code

  cashapp-burst:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/burst repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/burst
          submodules: true
          path: cashapp-burst
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-burst libraries.android-gradlePlugin key agp
          this/.github/helper.py patch-toml cashapp-burst versions.kotlin key kotlin
          this/.github/helper.py patch-toml cashapp-burst libraries.google-ksp key ksp
      - name: "Patch maven local"
        working-directory: cashapp-burst
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-burst
        run: git diff --patch
      - name: "Build cashapp-burst"
        working-directory: cashapp-burst
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-burst-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-burst/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-copper:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-turbine
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/copper repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/copper
          submodules: true
          path: cashapp-copper
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-copper libraries.android-gradlePlugin key agp
          this/.github/helper.py patch-toml cashapp-copper libraries.kotlin-gradlePlugin key kotlin
      - name: "Download internal dependency cashapp/turbine"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-turbine.result == 'success' }}
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/turbine"
        run: this/.github/helper.py patch-toml cashapp-copper libraries.turbine value ${{ needs.cashapp-turbine.outputs.version }}
        if: ${{ needs.cashapp-turbine.result == 'success' }}
      - name: "Patch maven local"
        working-directory: cashapp-copper
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-copper
        run: git diff --patch
      - name: "Build cashapp-copper"
        working-directory: cashapp-copper
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-copper-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-copper/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-licensee:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-kotlinpoet
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/licensee repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/licensee
          submodules: true
          path: cashapp-licensee
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-licensee versions.agp key agp
          this/.github/helper.py patch-toml cashapp-licensee versions.kotlin key kotlin
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml cashapp-licensee libraries.kotlinpoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Patch maven local"
        working-directory: cashapp-licensee
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-licensee
        run: git diff --patch
      - name: "Build cashapp-licensee"
        working-directory: cashapp-licensee
        run: ../this/gradlew --continue publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-licensee-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-licensee/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-molecule:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-turbine
      - square-moshi
      - square-okhttp
      - square-retrofit
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/molecule repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/molecule
          submodules: true
          path: cashapp-molecule
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-molecule libraries.android-plugin key agp
          this/.github/helper.py patch-toml cashapp-molecule versions.jetbrains-compose key jbCompose
          this/.github/helper.py patch-toml cashapp-molecule versions.kotlin key kotlin
      - name: "Download internal dependency cashapp/turbine"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-turbine.result == 'success' }}
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/turbine"
        run: this/.github/helper.py patch-toml cashapp-molecule libraries.turbine value ${{ needs.cashapp-turbine.outputs.version }}
        if: ${{ needs.cashapp-turbine.result == 'success' }}
      - name: "Download internal dependency square/moshi"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-moshi.result == 'success' }}
        with:
          name: square-moshi-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/moshi"
        run: this/.github/helper.py patch-toml cashapp-molecule versions.com-squareup-moshi value ${{ needs.square-moshi.outputs.version }}
        if: ${{ needs.square-moshi.result == 'success' }}
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml cashapp-molecule versions.squareup-okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Download internal dependency square/retrofit"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-retrofit.result == 'success' }}
        with:
          name: square-retrofit-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/retrofit"
        run: this/.github/helper.py patch-toml cashapp-molecule versions.squareup-retrofit value ${{ needs.square-retrofit.outputs.version }}
        if: ${{ needs.square-retrofit.result == 'success' }}
      - name: "Patch maven local"
        working-directory: cashapp-molecule
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-molecule
        run: git diff --patch
      - name: "Build cashapp-molecule"
        working-directory: cashapp-molecule
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-molecule-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-molecule/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-paraphrase:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-kotlinpoet
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/paraphrase repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/paraphrase
          submodules: true
          path: cashapp-paraphrase
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-paraphrase versions.agp key agp
          this/.github/helper.py patch-toml cashapp-paraphrase versions.kotlin key kotlin
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml cashapp-paraphrase libraries.kotlinPoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Patch maven local"
        working-directory: cashapp-paraphrase
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-paraphrase
        run: git diff --patch
      - name: "Build cashapp-paraphrase"
        working-directory: cashapp-paraphrase
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-paraphrase-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-paraphrase/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-redwood:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-burst
      - cashapp-turbine
      - square-kotlinpoet
      - square-okio
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/redwood repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/redwood
          submodules: true
          path: cashapp-redwood
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-redwood libraries.androidGradlePlugin key agp
          this/.github/helper.py patch-toml cashapp-redwood libraries.atomicFuPlugin key atomicfu
          this/.github/helper.py patch-toml cashapp-redwood versions.jbCompose key jbCompose
          this/.github/helper.py patch-toml cashapp-redwood versions.kotlin key kotlin
          this/.github/helper.py patch-toml cashapp-redwood versions.ksp key ksp
      - name: "Download internal dependency cashapp/burst"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-burst.result == 'success' }}
        with:
          name: cashapp-burst-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/burst"
        run: this/.github/helper.py patch-toml cashapp-redwood versions.burst value ${{ needs.cashapp-burst.outputs.version }}
        if: ${{ needs.cashapp-burst.result == 'success' }}
      - name: "Download internal dependency cashapp/turbine"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-turbine.result == 'success' }}
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/turbine"
        run: this/.github/helper.py patch-toml cashapp-redwood libraries.turbine value ${{ needs.cashapp-turbine.outputs.version }}
        if: ${{ needs.cashapp-turbine.result == 'success' }}
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml cashapp-redwood libraries.kotlinPoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml cashapp-redwood versions.okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml cashapp-redwood libraries.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: cashapp-redwood
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-redwood
        run: git diff --patch
      - name: "Build cashapp-redwood"
        working-directory: cashapp-redwood
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal -x :redwood-treehouse-host:check
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-redwood-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/REDWOOD_VERSION = "(.*)"/ and print "version=$1",$/' cashapp-redwood/build-support/src/main/kotlin/app/cash/redwood/buildsupport/RedwoodBuildPlugin.kt >> "$GITHUB_OUTPUT"

  cashapp-turbine:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout cashapp/turbine repository"
        uses: actions/checkout@v5
        with:
          repository: cashapp/turbine
          submodules: true
          path: cashapp-turbine
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml cashapp-turbine plugins.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: cashapp-turbine
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: cashapp-turbine
        run: git diff --patch
      - name: "Build cashapp-turbine"
        working-directory: cashapp-turbine
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-turbine/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-cite:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/cite repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/cite
          submodules: true
          path: JakeWharton-cite
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-cite libraries.android-gradlePlugin key agp
          this/.github/helper.py patch-toml JakeWharton-cite versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-cite
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-cite
        run: git diff --patch
      - name: "Build JakeWharton-cite"
        working-directory: JakeWharton-cite
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-cite-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-cite/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-confundus:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/confundus repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/confundus
          submodules: true
          path: JakeWharton-confundus
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-confundus versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-confundus
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-confundus
        run: git diff --patch
      - name: "Build JakeWharton-confundus"
        working-directory: JakeWharton-confundus
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-confundus-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-confundus/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-crossword:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/crossword repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/crossword
          submodules: true
          path: JakeWharton-crossword
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-crossword libraries.kotlinPlugin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-crossword
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-crossword
        run: git diff --patch
      - name: "Build JakeWharton-crossword"
        working-directory: JakeWharton-crossword
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-crossword-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-crossword/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-dependency-tree-diff:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/dependency-tree-diff repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/dependency-tree-diff
          submodules: true
          path: JakeWharton-dependency-tree-diff
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-dependency-tree-diff libraries.kotlin-gradle-plugin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-dependency-tree-diff
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-dependency-tree-diff
        run: git diff --patch
      - name: "Build JakeWharton-dependency-tree-diff"
        working-directory: JakeWharton-dependency-tree-diff
        run: ../this/gradlew --continue build

  JakeWharton-dependency-watch:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/dependency-watch repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/dependency-watch
          submodules: true
          path: JakeWharton-dependency-watch
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-dependency-watch versions.kotlin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml JakeWharton-dependency-watch versions.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-dependency-watch
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-dependency-watch
        run: git diff --patch
      - name: "Build JakeWharton-dependency-watch"
        working-directory: JakeWharton-dependency-watch
        run: ../this/gradlew --continue build

  JakeWharton-diffuse:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okio
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/diffuse repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/diffuse
          submodules: true
          path: JakeWharton-diffuse
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-diffuse libraries.apkSigner key agp
          this/.github/helper.py patch-toml JakeWharton-diffuse libraries.kotlinPlugin key kotlin
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml JakeWharton-diffuse libraries.okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-diffuse
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-diffuse
        run: git diff --patch
      - name: "Build JakeWharton-diffuse"
        working-directory: JakeWharton-diffuse
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-diffuse-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-diffuse/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-finalization-hook:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/finalization-hook repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/finalization-hook
          submodules: true
          path: JakeWharton-finalization-hook
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-finalization-hook versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-finalization-hook
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-finalization-hook
        run: git diff --patch
      - name: "Build JakeWharton-finalization-hook"
        working-directory: JakeWharton-finalization-hook
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-finalization-hook-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-finalization-hook/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-gitout:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/gitout repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/gitout
          submodules: true
          path: JakeWharton-gitout
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-gitout versions.kotlin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml JakeWharton-gitout versions.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-gitout
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-gitout
        run: git diff --patch
      - name: "Build JakeWharton-gitout"
        working-directory: JakeWharton-gitout
        run: ../this/gradlew --continue build

  JakeWharton-hardcover-data-sync:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/hardcover-data-sync repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/hardcover-data-sync
          submodules: true
          path: JakeWharton-hardcover-data-sync
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-hardcover-data-sync libraries.kotlin-gradlePlugin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml JakeWharton-hardcover-data-sync versions.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-hardcover-data-sync
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-hardcover-data-sync
        run: git diff --patch
      - name: "Build JakeWharton-hardcover-data-sync"
        working-directory: JakeWharton-hardcover-data-sync
        run: ../this/gradlew --continue build

  JakeWharton-jakewharton-com:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/jakewharton.com repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/jakewharton.com
          submodules: true
          path: JakeWharton-jakewharton-com
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-jakewharton-com libraries.kotlinGradlePlugin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml JakeWharton-jakewharton-com libraries.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-jakewharton-com
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-jakewharton-com
        run: git diff --patch
      - name: "Build JakeWharton-jakewharton-com"
        working-directory: JakeWharton-jakewharton-com
        run: ../this/gradlew --continue build

  JakeWharton-kmp-missing-targets:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/kmp-missing-targets repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/kmp-missing-targets
          submodules: true
          path: JakeWharton-kmp-missing-targets
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-kmp-missing-targets libraries.android-gradlePlugin key agp
          this/.github/helper.py patch-toml JakeWharton-kmp-missing-targets versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-kmp-missing-targets
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-kmp-missing-targets
        run: git diff --patch
      - name: "Build JakeWharton-kmp-missing-targets"
        working-directory: JakeWharton-kmp-missing-targets
        run: ../this/gradlew --continue publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-kmp-missing-targets-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-kmp-missing-targets/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-mosaic:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - JakeWharton-cite
      - JakeWharton-finalization-hook
      - JakeWharton-test-distribution-gradle-plugin
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/mosaic repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/mosaic
          submodules: true
          path: JakeWharton-mosaic
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-mosaic versions.jetbrains-compose key jbCompose
          this/.github/helper.py patch-toml JakeWharton-mosaic versions.kotlin key kotlin
      - name: "Download internal dependency JakeWharton/cite"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-cite.result == 'success' }}
        with:
          name: JakeWharton-cite-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/cite"
        run: this/.github/helper.py patch-toml JakeWharton-mosaic libraries.citeGradlePlugin value ${{ needs.JakeWharton-cite.outputs.version }}
        if: ${{ needs.JakeWharton-cite.result == 'success' }}
      - name: "Download internal dependency JakeWharton/finalization-hook"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-finalization-hook.result == 'success' }}
        with:
          name: JakeWharton-finalization-hook-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/finalization-hook"
        run: this/.github/helper.py patch-toml JakeWharton-mosaic libraries.finalizationHook value ${{ needs.JakeWharton-finalization-hook.outputs.version }}
        if: ${{ needs.JakeWharton-finalization-hook.result == 'success' }}
      - name: "Download internal dependency JakeWharton/test-distribution-gradle-plugin"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-test-distribution-gradle-plugin.result == 'success' }}
        with:
          name: JakeWharton-test-distribution-gradle-plugin-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/test-distribution-gradle-plugin"
        run: this/.github/helper.py patch-toml JakeWharton-mosaic libraries.testDistributionGradlePlugin value ${{ needs.JakeWharton-test-distribution-gradle-plugin.outputs.version }}
        if: ${{ needs.JakeWharton-test-distribution-gradle-plugin.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-mosaic
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-mosaic
        run: git diff --patch
      - name: "Build JakeWharton-mosaic"
        working-directory: JakeWharton-mosaic
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-mosaic-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-mosaic/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-picnic:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - JakeWharton-crossword
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/picnic repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/picnic
          submodules: true
          path: JakeWharton-picnic
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-picnic libraries.kotlinPlugin key kotlin
      - name: "Download internal dependency JakeWharton/crossword"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-crossword.result == 'success' }}
        with:
          name: JakeWharton-crossword-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/crossword"
        run: this/.github/helper.py patch-toml JakeWharton-picnic libraries.crossword value ${{ needs.JakeWharton-crossword.outputs.version }}
        if: ${{ needs.JakeWharton-crossword.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-picnic
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-picnic
        run: git diff --patch
      - name: "Build JakeWharton-picnic"
        working-directory: JakeWharton-picnic
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-picnic-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-picnic/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-plex-auto-trash:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/plex-auto-trash repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/plex-auto-trash
          submodules: true
          path: JakeWharton-plex-auto-trash
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-plex-auto-trash versions.kotlin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml JakeWharton-plex-auto-trash versions.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Patch maven local"
        working-directory: JakeWharton-plex-auto-trash
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-plex-auto-trash
        run: git diff --patch
      - name: "Build JakeWharton-plex-auto-trash"
        working-directory: JakeWharton-plex-auto-trash
        run: ../this/gradlew --continue build

  JakeWharton-singular-solution:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/singular-solution repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/singular-solution
          submodules: true
          path: JakeWharton-singular-solution
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-singular-solution libraries.kotlin-gradlePlugin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-singular-solution
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-singular-solution
        run: git diff --patch
      - name: "Build JakeWharton-singular-solution"
        working-directory: JakeWharton-singular-solution
        run: ../this/gradlew --continue build

  JakeWharton-test-distribution-gradle-plugin:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/test-distribution-gradle-plugin repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/test-distribution-gradle-plugin
          submodules: true
          path: JakeWharton-test-distribution-gradle-plugin
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-test-distribution-gradle-plugin libraries.android-gradlePlugin key agp
          this/.github/helper.py patch-toml JakeWharton-test-distribution-gradle-plugin versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-test-distribution-gradle-plugin
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-test-distribution-gradle-plugin
        run: git diff --patch
      - name: "Build JakeWharton-test-distribution-gradle-plugin"
        working-directory: JakeWharton-test-distribution-gradle-plugin
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-test-distribution-gradle-plugin-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-test-distribution-gradle-plugin/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-timber:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/timber repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/timber
          submodules: true
          path: JakeWharton-timber
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-timber versions.agp key agp
          this/.github/helper.py patch-toml JakeWharton-timber versions.kotlin key kotlin
      - name: "Patch maven local"
        working-directory: JakeWharton-timber
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-timber
        run: git diff --patch
      - name: "Build JakeWharton-timber"
        working-directory: JakeWharton-timber
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-timber-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-timber/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-video-swatch:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-okio
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout JakeWharton/video-swatch repository"
        uses: actions/checkout@v5
        with:
          repository: JakeWharton/video-swatch
          submodules: true
          path: JakeWharton-video-swatch
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml JakeWharton-video-swatch versions.kotlin key kotlin
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml JakeWharton-video-swatch libraries.okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - run: brew install ffmpeg
      - name: "Patch maven local"
        working-directory: JakeWharton-video-swatch
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: JakeWharton-video-swatch
        run: git diff --patch
      - name: "Build JakeWharton-video-swatch"
        working-directory: JakeWharton-video-swatch
        run: ../this/gradlew --continue build

  sqldelight-Grammar-Kit-Composer:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-kotlinpoet
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout sqldelight/Grammar-Kit-Composer repository"
        uses: actions/checkout@v5
        with:
          repository: sqldelight/Grammar-Kit-Composer
          submodules: true
          path: sqldelight-Grammar-Kit-Composer
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml sqldelight-Grammar-Kit-Composer plugins.kotlinJvm key kotlin
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml sqldelight-Grammar-Kit-Composer libraries.kotlinPoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Patch maven local"
        working-directory: sqldelight-Grammar-Kit-Composer
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: sqldelight-Grammar-Kit-Composer
        run: git diff --patch
      - name: "Build sqldelight-Grammar-Kit-Composer"
        working-directory: sqldelight-Grammar-Kit-Composer
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: sqldelight-Grammar-Kit-Composer-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' sqldelight-Grammar-Kit-Composer/gradle.properties >> "$GITHUB_OUTPUT"

  sqldelight-sql-psi:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - sqldelight-Grammar-Kit-Composer
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout sqldelight/sql-psi repository"
        uses: actions/checkout@v5
        with:
          repository: sqldelight/sql-psi
          submodules: true
          path: sqldelight-sql-psi
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml sqldelight-sql-psi versions.kotlin key kotlin
      - name: "Download internal dependency sqldelight/Grammar-Kit-Composer"
        uses: actions/download-artifact@v5
        if: ${{ needs.sqldelight-Grammar-Kit-Composer.result == 'success' }}
        with:
          name: sqldelight-Grammar-Kit-Composer-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency sqldelight/Grammar-Kit-Composer"
        run: this/.github/helper.py patch-toml sqldelight-sql-psi plugins.grammarKitComposer value ${{ needs.sqldelight-Grammar-Kit-Composer.outputs.version }}
        if: ${{ needs.sqldelight-Grammar-Kit-Composer.result == 'success' }}
      - name: "Patch maven local"
        working-directory: sqldelight-sql-psi
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: sqldelight-sql-psi
        run: git diff --patch
      - name: "Build sqldelight-sql-psi"
        working-directory: sqldelight-sql-psi
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: sqldelight-sql-psi-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' sqldelight-sql-psi/gradle.properties >> "$GITHUB_OUTPUT"

  sqldelight-sqldelight:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-turbine
      - JakeWharton-picnic
      - sqldelight-Grammar-Kit-Composer
      - sqldelight-sql-psi
      - square-kotlinpoet
      - square-moshi
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout sqldelight/sqldelight repository"
        uses: actions/checkout@v5
        with:
          repository: sqldelight/sqldelight
          submodules: true
          path: sqldelight-sqldelight
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml sqldelight-sqldelight versions.agp key agp
          this/.github/helper.py patch-toml sqldelight-sqldelight libraries.kotlinx-atomicfu-plugin key atomicfu
          this/.github/helper.py patch-toml sqldelight-sqldelight versions.kotlin key kotlin
          this/.github/helper.py patch-toml sqldelight-sqldelight plugins.ksp key ksp
      - name: "Download internal dependency cashapp/turbine"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-turbine.result == 'success' }}
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/turbine"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight libraries.turbine value ${{ needs.cashapp-turbine.outputs.version }}
        if: ${{ needs.cashapp-turbine.result == 'success' }}
      - name: "Download internal dependency JakeWharton/picnic"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-picnic.result == 'success' }}
        with:
          name: JakeWharton-picnic-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/picnic"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight libraries.picnic value ${{ needs.JakeWharton-picnic.outputs.version }}
        if: ${{ needs.JakeWharton-picnic.result == 'success' }}
      - name: "Download internal dependency sqldelight/Grammar-Kit-Composer"
        uses: actions/download-artifact@v5
        if: ${{ needs.sqldelight-Grammar-Kit-Composer.result == 'success' }}
        with:
          name: sqldelight-Grammar-Kit-Composer-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency sqldelight/Grammar-Kit-Composer"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight plugins.grammarKitComposer value ${{ needs.sqldelight-Grammar-Kit-Composer.outputs.version }}
        if: ${{ needs.sqldelight-Grammar-Kit-Composer.result == 'success' }}
      - name: "Download internal dependency sqldelight/sql-psi"
        uses: actions/download-artifact@v5
        if: ${{ needs.sqldelight-sql-psi.result == 'success' }}
        with:
          name: sqldelight-sql-psi-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency sqldelight/sql-psi"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight versions.sqlPsi value ${{ needs.sqldelight-sql-psi.outputs.version }}
        if: ${{ needs.sqldelight-sql-psi.result == 'success' }}
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight libraries.kotlinPoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Download internal dependency square/moshi"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-moshi.result == 'success' }}
        with:
          name: square-moshi-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/moshi"
        run: this/.github/helper.py patch-toml sqldelight-sqldelight versions.moshi value ${{ needs.square-moshi.outputs.version }}
        if: ${{ needs.square-moshi.result == 'success' }}
      - name: "Patch maven local"
        working-directory: sqldelight-sqldelight
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: sqldelight-sqldelight
        run: git diff --patch
      - name: "Build sqldelight-sqldelight"
        working-directory: sqldelight-sqldelight
        run: ../this/gradlew --continue kotlinUpgradeYarnLock kotlinWasmUpgradeYarnLock build publishToMavenLocal -x dockerTest
      - uses: actions/upload-artifact@v4
        with:
          name: sqldelight-sqldelight-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' sqldelight-sqldelight/gradle.properties >> "$GITHUB_OUTPUT"

  square-kotlinpoet:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/kotlinpoet repository"
        uses: actions/checkout@v5
        with:
          repository: square/kotlinpoet
          submodules: true
          path: square-kotlinpoet
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-kotlinpoet versions.kotlin key kotlin
          this/.github/helper.py patch-toml square-kotlinpoet versions.ksp key ksp
      - name: "Patch maven local"
        working-directory: square-kotlinpoet
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-kotlinpoet
        run: git diff --patch
      - name: "Build square-kotlinpoet"
        working-directory: square-kotlinpoet
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-kotlinpoet/gradle.properties >> "$GITHUB_OUTPUT"

  square-moshi:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-kotlinpoet
      - square-okio
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/moshi repository"
        uses: actions/checkout@v5
        with:
          repository: square/moshi
          submodules: true
          path: square-moshi
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-moshi versions.kotlin key kotlin
          this/.github/helper.py patch-toml square-moshi versions.ksp key ksp
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml square-moshi versions.kotlinpoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml square-moshi libraries.okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Patch maven local"
        working-directory: square-moshi
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-moshi
        run: git diff --patch
      - name: "Build square-moshi"
        working-directory: square-moshi
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-moshi-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/version = "(.*)"/ and print "version=$1",$/' square-moshi/build.gradle.kts >> "$GITHUB_OUTPUT"

  square-okio:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-burst
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/okio repository"
        uses: actions/checkout@v5
        with:
          repository: square/okio
          submodules: true
          path: square-okio
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-okio versions.kotlin key kotlin
          this/.github/helper.py patch-toml square-okio libraries.android-gradle-plugin key agp
      - name: "Download internal dependency cashapp/burst"
        uses: actions/download-artifact@v5
        if: ${{ needs.cashapp-burst.result == 'success' }}
        with:
          name: cashapp-burst-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/burst"
        run: this/.github/helper.py patch-toml square-okio libraries.burst-gradle-plugin value ${{ needs.cashapp-burst.outputs.version }}
        if: ${{ needs.cashapp-burst.result == 'success' }}
      - name: "Patch maven local"
        working-directory: square-okio
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-okio
        run: git diff --patch
      - name: "Build square-okio"
        working-directory: square-okio
        run: ../this/gradlew --continue kotlinUpgradeYarnLock build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-okio/gradle.properties >> "$GITHUB_OUTPUT"

  square-okhttp:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okio
      - square-kotlinpoet
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/okhttp repository"
        uses: actions/checkout@v5
        with:
          repository: square/okhttp
          submodules: true
          path: square-okhttp
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-okhttp versions.org-jetbrains-kotlin key kotlin
          this/.github/helper.py patch-toml square-okhttp versions.ksp key ksp
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml square-okhttp versions.com-squareup-okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Download internal dependency square/kotlinpoet"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
        with:
          name: square-kotlinpoet-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/kotlinpoet"
        run: this/.github/helper.py patch-toml square-okhttp libraries.squareup-kotlinPoet value ${{ needs.square-kotlinpoet.outputs.version }}
        if: ${{ needs.square-kotlinpoet.result == 'success' }}
      - name: "Patch maven local"
        working-directory: square-okhttp
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-okhttp
        run: git diff --patch
      - name: "Build square-okhttp"
        working-directory: square-okhttp
        run: ../this/gradlew --continue publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/version = (.*)/ and print "version=$1",$/' square-okhttp/build.gradle.kts >> "$GITHUB_OUTPUT"

  square-retrofit:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okhttp
      - square-moshi
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/retrofit repository"
        uses: actions/checkout@v5
        with:
          repository: square/retrofit
          submodules: true
          path: square-retrofit
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-retrofit libraries.androidPlugin key agp
          this/.github/helper.py patch-toml square-retrofit versions.kotlin key kotlin
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: this/.github/helper.py patch-toml square-retrofit versions.okhttp value ${{ needs.square-okhttp.outputs.version }}
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Download internal dependency square/moshi"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-moshi.result == 'success' }}
        with:
          name: square-moshi-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/moshi"
        run: this/.github/helper.py patch-toml square-retrofit libraries.moshi value ${{ needs.square-moshi.outputs.version }}
        if: ${{ needs.square-moshi.result == 'success' }}
      - name: "Patch maven local"
        working-directory: square-retrofit
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-retrofit
        run: git diff --patch
      - name: "Build square-retrofit"
        working-directory: square-retrofit
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-retrofit-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-retrofit/gradle.properties >> "$GITHUB_OUTPUT"

  square-zstd-kmp:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - JakeWharton-test-distribution-gradle-plugin
      - square-okio
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          path: this
      - name: "Checkout square/zstd-kmp repository"
        uses: actions/checkout@v5
        with:
          repository: square/zstd-kmp
          submodules: true
          path: square-zstd-kmp
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: "Patch external dependencies"
        run: |
          pip install -r this/.github/requirements.txt
          this/.github/helper.py patch-toml square-zstd-kmp libraries.android-gradle-plugin key agp
          this/.github/helper.py patch-toml square-zstd-kmp versions.kotlin key kotlin
      - name: "Download internal dependency JakeWharton/test-distribution-gradle-plugin"
        uses: actions/download-artifact@v5
        if: ${{ needs.JakeWharton-test-distribution-gradle-plugin.result == 'success' }}
        with:
          name: JakeWharton-test-distribution-gradle-plugin-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency JakeWharton/test-distribution-gradle-plugin"
        run: this/.github/helper.py patch-toml square-zstd-kmp libraries.testDistributionGradlePlugin value ${{ needs.JakeWharton-test-distribution-gradle-plugin.outputs.version }}
        if: ${{ needs.JakeWharton-test-distribution-gradle-plugin.result == 'success' }}
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v5
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: this/.github/helper.py patch-toml square-zstd-kmp versions.okio value ${{ needs.square-okio.outputs.version }}
        if: ${{ needs.square-okio.result == 'success' }}
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build -p src/jvmMain/resources/jni
        working-directory: square-zstd-kmp/zstd-kmp
      - name: "Patch maven local"
        working-directory: square-zstd-kmp
        run: git grep -l 'mavenCentral()' '*.gradle*' | xargs sed -i "" -E 's/^([[:space:]]+)mavenCentral\(\)$/\1mavenLocal()\n\1mavenCentral()/g'
      - name: "Show local change diff"
        working-directory: square-zstd-kmp
        run: git diff --patch
      - name: "Build square-zstd-kmp"
        working-directory: square-zstd-kmp
        run: ../this/gradlew --continue build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-zstd-kmp-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-zstd-kmp/gradle.properties >> "$GITHUB_OUTPUT"

  final-status:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs:
      - workflow-up-to-date
      - cashapp-burst
      - cashapp-copper
      - cashapp-licensee
      - cashapp-molecule
      - cashapp-paraphrase
      - cashapp-redwood
      - cashapp-turbine
      - JakeWharton-cite
      - JakeWharton-confundus
      - JakeWharton-crossword
      - JakeWharton-dependency-tree-diff
      - JakeWharton-dependency-watch
      - JakeWharton-diffuse
      - JakeWharton-finalization-hook
      - JakeWharton-gitout
      - JakeWharton-hardcover-data-sync
      - JakeWharton-jakewharton-com
      - JakeWharton-kmp-missing-targets
      - JakeWharton-mosaic
      - JakeWharton-picnic
      - JakeWharton-plex-auto-trash
      - JakeWharton-singular-solution
      - JakeWharton-test-distribution-gradle-plugin
      - JakeWharton-timber
      - JakeWharton-video-swatch
      - sqldelight-Grammar-Kit-Composer
      - sqldelight-sql-psi
      - sqldelight-sqldelight
      - square-kotlinpoet
      - square-moshi
      - square-okio
      - square-okhttp
      - square-retrofit
      - square-zstd-kmp
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
