name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
  schedule:
    # 9:23 AM EST
    - cron: "23 13 * * *"

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dkotlin.incremental=false -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.logging.stacktrace=full"

jobs:
  workflow-up-to-date:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: brew update && brew install d2
      - run: pip install -r .github/requirements.txt
      - run: python3 .github/generate.py
      - run: git diff --exit-code

  cashapp-burst:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/burst
          path: cashapp-burst
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-burst/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Build cashapp/burst"
        run: |
          cd cashapp-burst
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-burst-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-burst/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-licensee:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/licensee
          path: cashapp-licensee
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-licensee/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path cashapp-licensee/gradle/libs.versions.toml versions.agp $(toml get --toml-path this/libs.versions.toml versions.agp)
      - name: "Build cashapp/licensee"
        run: |
          cd cashapp-licensee
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-licensee-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-licensee/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-molecule:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/molecule
          path: cashapp-molecule
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-molecule/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path cashapp-molecule/gradle/libs.versions.toml libraries.android-plugin.version $(toml get --toml-path this/libs.versions.toml versions.agp)
      - name: "Build cashapp/molecule"
        run: |
          cd cashapp-molecule
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-molecule-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-molecule/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-paraphrase:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/paraphrase
          path: cashapp-paraphrase
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-paraphrase/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path cashapp-paraphrase/gradle/libs.versions.toml versions.agp $(toml get --toml-path this/libs.versions.toml versions.agp)
      - name: "Build cashapp/paraphrase"
        run: |
          cd cashapp-paraphrase
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-paraphrase-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-paraphrase/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-turbine:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/turbine
          path: cashapp-turbine
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-turbine/gradle/libs.versions.toml plugins.kotlin.version $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Build cashapp/turbine"
        run: |
          cd cashapp-turbine
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-turbine-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-turbine/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-cite:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: JakeWharton/cite
          path: JakeWharton-cite
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path JakeWharton-cite/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Build JakeWharton/cite"
        run: |
          cd JakeWharton-cite
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-cite-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-cite/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-diffuse:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okio
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: JakeWharton/diffuse
          path: JakeWharton-diffuse
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path JakeWharton-diffuse/gradle/libs.versions.toml libraries.kotlinPlugin.version $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v4
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: toml set --toml-path JakeWharton-diffuse/gradle/libs.versions.toml libraries.okio.version "${{ needs.square-okio.outputs.version }}"
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Build JakeWharton/diffuse"
        run: |
          cd JakeWharton-diffuse
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-diffuse-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-diffuse/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-finalization-hook:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: JakeWharton/finalization-hook
          path: JakeWharton-finalization-hook
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path JakeWharton-finalization-hook/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Build JakeWharton/finalization-hook"
        run: |
          cd JakeWharton-finalization-hook
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: JakeWharton-finalization-hook-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' JakeWharton-finalization-hook/gradle.properties >> "$GITHUB_OUTPUT"

  JakeWharton-SaveArchived4Pocket:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    needs:
      - workflow-up-to-date
      - square-retrofit
      - square-okhttp
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: JakeWharton/SaveArchived4Pocket
          path: JakeWharton-SaveArchived4Pocket
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path JakeWharton-SaveArchived4Pocket/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Download internal dependency square/retrofit"
        uses: actions/download-artifact@v4
        if: ${{ needs.square-retrofit.result == 'success' }}
        with:
          name: square-retrofit-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/retrofit"
        run: toml set --toml-path JakeWharton-SaveArchived4Pocket/gradle/libs.versions.toml versions.retrofit "${{ needs.square-retrofit.outputs.version }}"
        if: ${{ needs.square-retrofit.result == 'success' }}
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v4
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: toml set --toml-path JakeWharton-SaveArchived4Pocket/gradle/libs.versions.toml versions.okhttp "${{ needs.square-okhttp.outputs.version }}"
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Build JakeWharton/SaveArchived4Pocket"
        run: |
          cd JakeWharton-SaveArchived4Pocket
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build

  square-okio:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-burst
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: square/okio
          path: square-okio
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path square-okio/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path square-okio/gradle/libs.versions.toml libraries.android-gradle-plugin.version $(toml get --toml-path this/libs.versions.toml versions.agp)
      - name: "Download internal dependency cashapp/burst"
        uses: actions/download-artifact@v4
        if: ${{ needs.cashapp-burst.result == 'success' }}
        with:
          name: cashapp-burst-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency cashapp/burst"
        run: toml set --toml-path square-okio/gradle/libs.versions.toml libraries.burst-gradle-plugin.version "${{ needs.cashapp-burst.outputs.version }}"
        if: ${{ needs.cashapp-burst.result == 'success' }}
      - name: "Build square/okio"
        run: |
          cd square-okio
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-okio/gradle.properties >> "$GITHUB_OUTPUT"

  square-okhttp:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okio
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: square/okhttp
          path: square-okhttp
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path square-okhttp/gradle/libs.versions.toml versions.org-jetbrains-kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
      - name: "Download internal dependency square/okio"
        uses: actions/download-artifact@v4
        if: ${{ needs.square-okio.result == 'success' }}
        with:
          name: square-okio-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okio"
        run: toml set --toml-path square-okhttp/gradle/libs.versions.toml versions.com-squareup-okio "${{ needs.square-okio.outputs.version }}"
        if: ${{ needs.square-okio.result == 'success' }}
      - name: "Build square/okhttp"
        run: |
          cd square-okhttp
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/version = (.*)/ and print "version=$1",$/' square-okhttp/build.gradle.kts >> "$GITHUB_OUTPUT"

  square-retrofit:
    runs-on: macos-latest
    if: ${{ !cancelled() }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - square-okhttp
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: square/retrofit
          path: square-retrofit
      - name: Patch external dependencies
        run: |
          pip install -q toml-cli
          toml set --toml-path square-retrofit/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path square-retrofit/gradle/libs.versions.toml libraries.androidPlugin.version $(toml get --toml-path this/libs.versions.toml versions.agp)
      - name: "Download internal dependency square/okhttp"
        uses: actions/download-artifact@v4
        if: ${{ needs.square-okhttp.result == 'success' }}
        with:
          name: square-okhttp-snapshot
          path: ~/.m2/repository
      - name: "Patch internal dependency square/okhttp"
        run: toml set --toml-path square-retrofit/gradle/libs.versions.toml versions.okhttp "${{ needs.square-okhttp.outputs.version }}"
        if: ${{ needs.square-okhttp.result == 'success' }}
      - name: "Build square/retrofit"
        run: |
          cd square-retrofit
          git grep -l mavenCentral | xargs sed -i "" "s/mavenCentral()/mavenLocal(); mavenCentral()/g"
          git diff --patch
          ../this/gradlew build publishToMavenLocal
      - uses: actions/upload-artifact@v4
        with:
          name: square-retrofit-snapshot
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-retrofit/gradle.properties >> "$GITHUB_OUTPUT"

  final-status:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs:
      - workflow-up-to-date
      - cashapp-burst
      - cashapp-licensee
      - cashapp-molecule
      - cashapp-paraphrase
      - cashapp-turbine
      - JakeWharton-cite
      - JakeWharton-diffuse
      - JakeWharton-finalization-hook
      - JakeWharton-SaveArchived4Pocket
      - square-okio
      - square-okhttp
      - square-retrofit
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
