name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dkotlin.incremental=false -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.logging.stacktrace=full"

jobs:
  workflow-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python3 generate.py
      - run: git diff --exit-code

  cashapp-burst:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/burst
          path: cashapp-burst
      - name: Patch versions
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-burst/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          cd cashapp-burst
          git diff --patch
      - run: ./gradlew check publishToMavenLocal
        working-directory: cashapp-burst
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-burst-maven-local
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-burst/gradle.properties >> "$GITHUB_OUTPUT"

  cashapp-turbine:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: cashapp/turbine
          path: cashapp-turbine
      - name: Patch versions
        run: |
          pip install -q toml-cli
          toml set --toml-path cashapp-turbine/gradle/libs.versions.toml plugins.kotlin.version $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          cd cashapp-turbine
          git diff --patch
      - run: ./gradlew check publishToMavenLocal
        working-directory: cashapp-turbine
      - uses: actions/upload-artifact@v4
        with:
          name: cashapp-turbine-maven-local
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' cashapp-turbine/gradle.properties >> "$GITHUB_OUTPUT"

  square-okio:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - workflow-up-to-date
      - cashapp-burst
    steps:
      - uses: actions/checkout@v4
        with:
          path: this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: this/.github/workflows/.java-version
      - uses: actions/checkout@v4
        with:
          repository: square/okio
          path: square-okio
      - name: Patch versions
        run: |
          pip install -q toml-cli
          toml set --toml-path square-okio/gradle/libs.versions.toml versions.kotlin $(toml get --toml-path this/libs.versions.toml versions.kotlin)
          toml set --toml-path square-okio/gradle/libs.versions.toml libraries.burst-gradle-plugin.version "${{ needs.cashapp-burst.outputs.version }}"
          cd square-okio
          git apply ../this/patches/square/okio.patch
          git diff --patch
      - run: ./gradlew check publishToMavenLocal
        working-directory: square-okio
      - uses: actions/download-artifact@v4
        with:
          name: cashapp-burst-maven-local
          path: ~/.m2/repository
      - uses: actions/upload-artifact@v4
        with:
          name: square-okio-maven-local
          path: ~/.m2/repository
          if-no-files-found: error
      - id: version
        run: perl -ne '/VERSION_NAME=(.*)/ and print "version=$1",$/' square-okio/gradle.properties >> "$GITHUB_OUTPUT"

  final-status:
    runs-on: ubuntu-latest
    needs:
      - cashapp-burst
      - cashapp-turbine
      - square-okio
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
